name: Build StructCoderEnvironment image
on:
  workflow_dispatch:
  push:
    paths:
      - containers/structcoder-env/Dockerfile
      - .github/workflows/structcoder-env-cbuild.yml # Self-trigger

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: misakagaming/structcoder-env
  VERSION: latest

jobs:

  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: containers/structcoder-env
          build-args: |
            VERSION=${{ env.VERSION }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max